update workflow

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -7,7 +7,7 @@ on:
       - main
 
 env:
-  FLUTTER_CHANNEL: "stable"
+  BUILD_NAME: "1.0.${{ github.run_number }}"
 
 jobs:
   build_android:
@@ -34,22 +34,35 @@ jobs:
           storeFile=../key.jks
           EOF
 
+      - name: Fetch dependencies
+        run: flutter pub get
+      
+      - name: Check generated files are up to date
+        run: |
+          dart run build_runner build --delete-conflicting-outputs
+
+          if [[ -n "$(git status --porcelain)" ]]; then
+            git status --porcelain
+            echo "::error title=Generated files out of date::Generated files are out of date"
+            exit 1
+          fi
+
       - name: Build
         run: |
-          flutter build appbundle --release --build-number="${{ github.run_number }}" --build-name="1.0.${{ github.run_number }}"
-          flutter build apk --debug --build-number="${{ github.run_number }}" --build-name="1.0.${{ github.run_number }}"
+          flutter build appbundle --release --build-number="${{ github.run_number }}" --build-name="${{ env.BUILD_NAME }}"
+          flutter build apk --debug --build-number="${{ github.run_number }}" --build-name="${{ env.BUILD_NAME }}"
 
       - name: Archive App Bundle
         uses: actions/upload-artifact@v5
         with:
-          name: "subspace_relay_mobile_aab_release_v${{ github.run_number }}"
+          name: "subspace_relay_mobile_aab_release_v${{ env.BUILD_NAME }}"
           path: build/app/outputs/bundle/release/app-release.aab
           if-no-files-found: error
 
       - name: Archive APK
         uses: actions/upload-artifact@v5
         with:
-          name: "subspace_relay_mobile_apk_debug_v${{ github.run_number }}"
+          name: "subspace_relay_mobile_apk_debug_v${{ env.BUILD_NAME }}"
           path: build/app/outputs/flutter-apk/app-debug.apk
           if-no-files-found: error
 
@@ -57,14 +70,14 @@ jobs:
         uses: google-github-actions/auth@v2
         id: auth
         with:
-          service_account: '${{ env.GCP_SERVICE_ACCOUNT }}'
-          workload_identity_provider: '${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
+          service_account: '${{ vars.GCP_SERVICE_ACCOUNT }}'
+          workload_identity_provider: '${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
 
       - uses: r0adkll/upload-google-play@v1
         with:
           serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
           releaseFiles: build/app/outputs/bundle/release/app-release.aab
           packageName: io.nv.subspacerelay.mobile
-          releaseName: "1.0.${{ github.run_number }}"
+          releaseName: "${{ env.BUILD_NAME }}"
           track: internal
           status: draft
